# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.define :linux1 do |config|
    config.vm.box = "ubuntu-11.04-amd64-with-jre"
    config.vm.customize ["modifyvm", :id, "--memory", "512"]
    config.vm.network :hostonly, "33.33.33.13"
  end

  config.vm.define :linux2 do |config|
    config.vm.box = "ubuntu-11.04-amd64-with-jre"
    config.vm.customize ["modifyvm", :id, "--memory", "512"]
    config.vm.network :hostonly, "33.33.33.14"
  end

  config.vm.define :linux3 do |config|
    config.vm.box = "ubuntu-11.04-amd64-with-jre"
    config.vm.customize ["modifyvm", :id, "--memory", "512"]
    config.vm.network :hostonly, "33.33.33.15"
  end
end
